version: '3.8'
services:
  rocksdb:
    image: rocksdb
    # build: .
    container_name: rocksdb
    # tty: true
    volumes:
      - db_data:/data
    # networks:
    #   - rocksdb
    # command: ["./db_bench", "-benchmarks=fillseq", "-compression-type=none", "-db=/data/" ]
    command: bash -c "cd /usr/src/rocksdb/build && ./db_bench -benchmarks=fillseq -compression-type=none -db=/data/ && tail -f /dev/null"
    ports:
      - "8080:8080"
    working_dir:
      /usr/src/rocksdb/build
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib

volumes:
  db_data:
    # driver: local
