version: '3.8'
services:
  rocksdb:
    image: rocksdb
    # build: .
    container_name: rocksdb
    volumes:
      - ./data:/data
    # networks:
    #   - rocksdb
    command: ["./db_bench", "-benchmarks=fillseq", "-compression-type=none" ]
    ports:
      - "8080:8080"
    working_dir:
      /usr/src/rocksdb/build
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib

